### ISSUE TITLE
OS X - "Cannot read the contents of a file" exception

### ISSUE THREAD

**Issue by ericwa** [GPUOpen-LibrariesAndSDKs/FireRays_SDK#34]
This exception is thrown in `load_file_contents` when trying to load `"../FireRays/src/kernel/CL/bvh.cl"`.

It seems to be an issue of wrong working directory.
```
(lldb) print (char *)getwd(NULL)
(char *) $1 = 0x00000001078e7400 "/Users/ericwa/dev/FireRays_SDK/Bin/Debug/x64"
```
Editing the "App" scheme in Xcode to set a custom working directory of `/Users/ericwa/dev/FireRays_SDK/Bin` fixes the problem.

**Comment by yozhijk** [comment]
Usually I prefer to build the library with --embed_kernel premake option, this removes dependencies on kernels location.

**Comment by ericwa** [comment]
Ah I see, I didn't notice the part of README.md about running with the "App" subdirectory as the working dir.
This issue can probably be closed then.

**Comment by dylanlacewell** [comment]
Hi there.  Can you provide an example of using the --embed_kernels and --package options?  I would like to see all steps needed on Linux to get a dist package that does not have dependencies on the 'src' directory, so that it can be linked to a binary that is run anywhere on the machine.

I've tried the --embed_kernels option on Linux and still get the error above unless I run from the App directory.  I don't consider this a solution. Maybe I'm not invoking premake correctly (not much experience with this tool).

Thanks!

**Comment by yozhijk** [comment]
Hi @dylanlacewell,

The thing here is --embed_kernels premake option only affects FireRays library itself, but not the sample app. That means if link your own app against libFireRays.so you are fine and it does not require any external CL files. On the other hand if you are building your app based on the sample renderer you still need external CL files from App/CL directory. This is the limitation of the python script we are using to stringify our kernels (it can't handle relatively complex include hierarchy the sample app is using, need to add some functionality of a C preprocessor into it). I have just opened a separate ticket to track this issue: https://github.com/GPUOpen-LibrariesAndSDKs/FireRays_SDK/issues/55

**Comment by dylanlacewell** [comment]
Thanks for the reply.  I hit the exception in a call to FireRays::IntersectionApi::Create(). Not an external kernel.  I posted the stack trace in the other issue and will post any follow up comments over there.
