### ISSUE TITLE
Shading language (and. OptiX interaction suggestion)

### ISSUE THREAD

**Issue by acterhd** [GPUOpen-LibrariesAndSDKs/FireRays_SDK#38]
Hello. I suggest to add OptiX support in FireRays. For use in any GPU: from Nvidia to AMD. 

Also, have you shader language? 
For example: intersection or shading language for rays (like OpenRL)?

**Comment by yozhijk** [comment]
Hi @acterhd,

OptiX has proprietary license, so I am not sure we are allowed to. Anyway FireRays is supposed to work on Nvidia OpenCL (of course not as fast as on AMD), if it does not please file an issue here.

**Comment by yozhijk** [comment]
As for shading language: The language is OpenCL C currently, all the shaders for the sample rendrer are written in OpenCL C. However it is not comparable to OpenRL since you can't trace a ray from during shader execution, this is very inefficient on modern GPUs. Our shading approach is closer to Open Shading Language(OSL) where we describe surface appearance  and renderer evaluates it in the way it wants.
