### ISSUE TITLE
Documentation on the shading techniques and materials?

### ISSUE THREAD

**Issue by DuracellTurtle** [GPUOpen-LibrariesAndSDKs/FireRays_SDK#41]
Hi, I am not sure if this belongs here, but I don't know where else i could post it. I have been trying to understand the kinds of materials in the App. So far I believe that:

- kLambert is diffuse
- kIdealReflect is 0 roughness reflective
- kMicrofacetXyz are reflective with some roughness controlled by ns 
- kIdealRefract is 0 roughness transparent
- kFresnelBlend and kMix are used to mix 2 of the above

- Is there any way to get refraction with some roughness?
- I had no luck combining Lambert, Microfacet and IdealRefract. Is it possible?
- In a scene that I tried to render, light directly from emissive material doesn't pass through a window. It does only after it bounces off other objects (light from hdr enviroment does too). Why is that? (For windows I use FresnelBlend of IdealRefract and MicrofacetGGX and for opaque objects FresnelBlend of Lambert and MicrofacetGGX. Even if camera sees the emissive material through the window, it is black..)

PS: Just noticed that a "glass mask" is being set during Preprocess. What is the purpose? (Setting it for my transparent material did not help with the emissive light)

Thanks

**Comment by yozhijk** [comment]
Hi @DuracellTurtle ,

I did not do any documentation for the sample add since it was intended only to illustrate the usage of the library. However it seems like it is being developed into fully functional renderer maybe it is time to do so. I will try to write something up soon. Now regarding your points:

kLambert is obviously diffuse.
kIdealReflect is a perfect mirror,  correct.
kMicrofacetBlinn - Blinn distribution of mf normals
kMicrofacetGGX - GGX dist
kMicrofacetBeckmann - Beckmann dist
kIdealRefract - perfect refractor, based on IOR
kFresnelBlend - blend of two materials based on IOR (layering), basically F * M1 + (1-F) * M2, where F is angle dependent.

I did not have time to implement glossy refraction just yet, will hopefully do so next week (or go ahead and implement yourself, I would love to get pull requests and merge them)
Combining 3 materials are not currently possible, I will have to fix that (need to change material selection part in material.cl)

>>In a scene that I tried to render, light directly from emissive material doesn't pass through a window. It >>does only after it bounces off other objects (light from hdr enviroment does too). Why is that? (For >>windows I use FresnelBlend of IdealRefract and MicrofacetGGX and for opaque objects FresnelBlend >>of Lambert and MicrofacetGGX. Even if camera sees the emissive material through the window, it is >>black

I have done some update of the renderer today, could you try with the latest code? If still reproducible , could you send me a repro scene?

**Comment by DuracellTurtle** [comment]
Hey, thanks for fast response.
If I had some background and was able to do the blurry refraction properly, I would.
The update fixed the issue and my room is flooded with sunlight, as intended :)
Thanks

**Comment by yozhijk** [comment]
@DuracellTurtle , 

I had no luck combining Lambert, Microfacet and IdealRefract. Is it possible?

I implemented a fix for that, so now possible to blend kFresnelBlend and kMix nodes.

**Comment by yozhijk** [comment]
Attaching some tests with multilayered:

![app64 2016-06-23 20-10-50-51](https://cloud.githubusercontent.com/assets/4111901/16316117/306f3156-3985-11e6-8af5-29b0a602076e.jpg)
![app64 2016-06-23 20-36-26-54](https://cloud.githubusercontent.com/assets/4111901/16316118/3070a52c-3985-11e6-95ad-99790ce8f16a.jpg)
![app64 2016-06-23 20-39-13-03](https://cloud.githubusercontent.com/assets/4111901/16316119/30757110-3985-11e6-9cf5-42986a6a63a2.jpg)

**Comment by yozhijk** [comment]
@DuracellTurtle ,

I implemented initial version of glossy refraction here: https://github.com/GPUOpen-LibrariesAndSDKs/FireRays_SDK/commit/594d0d0525d80965e0f9de9aa18782331a0a31eb

It still has some issues like fireflies and messy Fresnel handling, I will clean that up and merge to master next week. 

![image](https://cloud.githubusercontent.com/assets/4111901/16525173/d0962372-3fb3-11e6-92fa-cb49b41dfd5b.png)

**Comment by yozhijk** [comment]
Fresnel handling is fixed here: https://github.com/GPUOpen-LibrariesAndSDKs/FireRays_SDK/commit/3cf0057e3f046894d47a8e9440cfb8c702d14780

I have also added Beckmann distribution for refraction.

![rough_glass](https://cloud.githubusercontent.com/assets/4111901/16561723/6d22749c-4203-11e6-8ab9-b4e255be1ad1.png)
![rough_glass_1](https://cloud.githubusercontent.com/assets/4111901/16561725/6f63be28-4203-11e6-88dc-67e706d09b4b.png)

**Comment by yozhijk** [comment]
Merged to master
